run:
		go run functions/testfunc.go
		go run functions/testclosures.go
		go run functions/testmultireturn.go
		go run functions/testvariaticfunc.go
		go run functions/testrecursion.go
		go run package/package.go
		