run:
		go run 8.1.pointers/testpointers.go
		go run 8.1.pointers/pointers_to_pointers.go
		go run 8.2.structures/teststructs.go
		go run 8.2.structures/any_struct.go
		go run 8.2.structures/struc_tag.go
		go run 8.4.interfaces/testinterfaces.go
		go run 8.4.interfaces/type_switch.go
		go run 8.3.methods/testmethods.go
		go run 8.4.interfaces/composite_interface.go