mysql:
		
		mysql -u root -p test
		#if you dont have the databse already
		#in the mysql prompt 
		#CREATE DATABASE test;
		#CREATE TABLE test(
			#id INT NOT NULL
		#);
run:
		go run db-dial.go
		go run db-insert.go

install-windows:
		choco install mysql
		mysql -u root -p

install-mac:
		brew install mysql
		mysql -u root -p
		
