run:
		go run channels/test-channels.go
		go run channels/test-channel-direction.go
		go run channels/test-channel-buffer.go
		go run routines/test-routines.go
		go run select/test-select.go
		go run select/test-ticker.go
		go run select/test-timeout.go
		go run state/stateful-routines.go
		go run state/test-counters.go
		go run state/test-mutex.go
		go run workerpool/test-workerpools.go
		go run workerpool/rate-limiting.go